CREATE TABLE `records` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `githubid` INTEGER NOT NULL DEFAULT NULL,
  `in` BIGINT NULL DEFAULT NULL,
  `out` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `rate_intervals` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `githubid` INTEGER NOT NULL DEFAULT NULL,
  `start` BIGINT NULL DEFAULT NULL,
  `rate` INTEGER NULL DEFAULT NULL,
  `currency` VARCHAR(3) NULL DEFAULT NULL,
  `currency_time` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `payments` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `githubid` INTEGER NOT NULL DEFAULT NULL,
  `amount` BIGINT NULL DEFAULT NULL,
  `currency` VARCHAR(3) NULL DEFAULT NULL,
  `currency_time` BIGINT NOT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

ALTER TABLE `records` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE `rate_intervals` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE `payments` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
